# Generated by Django 2.1.4 on 2019-05-18 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=45, verbose_name='TODO 제목')),
                ('todo_content', models.TextField(verbose_name='TODO 내용')),
                ('deadline', models.DateTimeField(null=True, verbose_name='기한')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
        ),
        migrations.CreateModel(
            name='TodoPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_rank', models.IntegerField(choices=[(0, '매우 중요'), (1, '중요'), (2, '보통'), (3, '사소'), (4, '매우 사소')], verbose_name='중요도')),
            ],
        ),
        migrations.CreateModel(
            name='TodoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '발의'), (1, '진행'), (2, '완료')], verbose_name='상태')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TodoPriority', verbose_name='중요도'),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TodoStatus', verbose_name='상태'),
        ),
    ]
