# Generated by Django 2.1.4 on 2019-05-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190519_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(0, '발의'), (1, '진행'), (2, '완료')], default=0, verbose_name='상태'),
        ),
    ]
